= dnsrblstats.py(8)
Klaus Tachtler
:doctype: manpage
:release-version: 0.1.
:man manual: dnsrblstats.py Manual
:man source: dnsrblstats.py {release-version}
:page-layout: base

== NAME

dnsrblstats.py - Program for the compression of log files, collected by the program godnsrblbench, for the creation of a compressed output file and optional a RBL statistic report file, in a certain output format, for the creation of statistics.

== SYNOPSIS

*dnsrblstats.py [-h] -i [FILE] -o [FILE] -s [FILE] [-v] [-d]*

== DESCRIPTION

Program for the compression of log files, collected by the program godnsrblbench, for the creation of a compressed output file,
in a certain output format, for the creation of statistics.

The _OPTION_ *-i, --inputfile* and the _OPTION_ *-o, --outputfile* are _REQUIRED_ and their parameter [_FILE_] are _also_ _REQUIRED_ for running the program.

== OPTIONS

=== Configuration parameter

*-i [FILE], --inputfile [FILE]*::
  [REQUIRED] Input file with statistic data generated by godnsrblbench.
  
*-o [FILE], --outputfile [FILE]*::
  [REQUIRED] Output file for compressed data.
  
*-s [FILE], --statsfile [FILE]*::
  Statistics file about the seen RBL and their use.

=== Debugging

*-d, --debug*::
  DEBUG mode with runtime output

=== Program Information

*-h, --help*::
  Print usage information

*-v, --version*::
  Version of the program

== ENVIRONMENT

_The following dependencies are required to run the program_:

Running *Python 3* from *version 3.6 or higher*.

== EXIT STATUS

*0*::
  Success.
  The -o, --outputfile [_FILE_] was successfully generated and written!

*>0*::
  Failure.
  The -o, --outputfile [_FILE_] was *NOT* successfully generated and written!

== OUTPUT FORMAT

The output format of the -o, --outputfile:

[source,ini]
....
Timestamp,ID,Hostname,Durationsummary,Durationaverage,Requestcounter,[CAN REPEAT MORE THAN ONCE: RBL-Request,Result,IP,Port,Duration]
....
_Example:_
[source,ini]
....
2019-06-24T12:29:25+00:00,2c50328c,echo,0.253928,0.084642,3,xxx.xxx.xxx.xxx.bl.mailspike.net,--,xxx.xxx.xxx.xxx,53,0.041785,...
....

The output format of the -s, --statsfile:
[source,ini]
....
RBL-Seen,RBL-Count,RBL-Durationsummary,RBL-Durationaverage
....
_Example:_
[source,ini]
....
mailspike.net,184,1.895781,0.010303157608696
....

== BUGS

Refer to the *dnsrblstats.py* issue tracker at https://github.com/sys4/godnsrblbench/issues?q=is%3Aopen.

== AUTHORS

*dnsrblstats.py* was written by Klaus Tachtler. mailto:k@sys4.de

*godnsrblbench.go* was written by Carsten Strotmann. mailto:cs@sys4.de

== RESOURCES

*Project web site:* https://github.com/sys4/godnsrblbench

== COPYING

Copyright \(C) 2019 Klaus Tachtler. Free use of this software is granted under the terms of the

  GNU GENERAL PUBLIC LICENSE
  Version 3, 29 June 2007

  Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
  Everyone is permitted to copy and distribute verbatim copies
  of this license document, but changing it is not allowed.
         
  https://www.gnu.org/licenses/gpl-3.0.txt
 
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  implied. See the License for the specific language governing
  permissions and limitations under the License.

  Distributed on an "AS IS" basis without warranties
  or conditions of any kind, either express or implied
